### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Amraish** [guillaumev/teca#88]
Dear , Charlotte published two technologies on 18 and 19 August but no notifications were sent. Could you please check whats wrong and if possible let them appear in the next notification. 

Thanks 
Nedaa

**Comment by guillaumev** [comment]
Hi Nedaa,

This technology: http://teca.fao.org/fr/node/8786/edit doesn't have the "Send notification" checkbox checked.

This one: http://teca.fao.org/node/8775 seems like it went through a lot of revisions... I'm not sure exactly what happened for this one, but I unpublished it and published it again, and it should go into the next notification email. Note that you can do the same for the other one if you wish (make sure the "Send notification" checkbox is checked, unpublish the technology, publish it again and it should work)

Closing this, feel free to reopen if needed.
